### ISSUE TITLE
Measurements: fermentables/malt

### ISSUE THREAD

**Issue by pricelessbrewing** [buildabeer/buildabeer#23]
Under measurements, it lists "grams" as the option for malt/fermentables, but when in the fermentables section is displays as (kg).

**Comment by eyesurewould** [comment]
Can you provide steps to re-create (or a URL for where this is observed)? I don't see the instance of 'grams'.

Also, I assume that 'kg' is the preferred option. Please confirm.

**Comment by buildabeer** [comment]
I have no idea what this is referencing anymore. I don't see a problem between measurement and fermentables. Closing as unreproducible.

**Comment by pricelessbrewing** [comment]
I'll take a look and try to reproduce with documentation tomorrow.

**Comment by buildabeer** [comment]
Oh, I think I know what it means. I didn't look at who initially filed the bug. Kg is kilograms. I think that's more appropriate than grams, but feel free to correct me. 

I would think (I dunno, I'm American) grams would be the appropriate label for the drop-down even if it will mostly be kilograms. Leaves the option later as well of the fermentables displaying grams of the count is low enough and automatically adjust to kg once above 1000.

I'll reopen until discussion is finished.

**Comment by eyesurewould** [comment]
The most analogous unit to lbs would be kg. A kilogram is roughly 2.2lbs.

If you're brewing with 15.5lbs of grain, you probably not say "248 oz". You'd say "15lbs 8oz". But in metric, it's perfectly normal to use decimals. For example, if you need 4kg of one grain and 8g of another, it's normal to say "the total grain bill is 4.8kg".

So, I'd suggest using kg for fermentables.

All that said.... Where does this situation occur (and do we have steps to reproduce)? I took another look but I must be in the wrong section.

**Comment by buildabeer** [comment]
He's referring to the fact that if you go to the measurements tab, the 'Weight (Fermentables)' menu has grams instead of kilograms listed as the option.

This does remind me, the fermentables tab does not use ounces along w/ pounds, just fractions.

**Comment by eyesurewould** [comment]
OK. Can you assign this to me?

**Comment by buildabeer** [comment]
Hmm, it doesn't list you as an option to assign it to.

**Comment by eyesurewould** [comment]
You might need to add me to the project in some way.

**Comment by pricelessbrewing** [comment]
I could be wrong but I think they have to be added to the organization for the repo, or one of the groups before an issue can be assigned.

**Comment by buildabeer-admin** [comment]
Well that was fun. Had to change my github name, create organization with it, transfer the repo, and then I could invite. But it is there! Hopefully I can assign after the invite is accepted.

**Comment by pricelessbrewing** [comment]
Yup that's a fun one. 

Note that there's consequences for changing a repo to an organization as far as licensing and IP.

**Comment by buildabeer-admin** [comment]
Beyond the open source licensing in the repo?

**Comment by pricelessbrewing** [comment]
Not really an issue as long as the project remains under a FOSS license. Just something to keep in mind so if it's new to you I wanted to give a heads up.
