### ISSUE TITLE
Bottom menu on mobile

### ISSUE THREAD

**Issue by buildabeer-admin** [buildabeer/buildabeer#50]
Should this menu get some form of dropdown condense like the top menu does? Currently it stacks them and creates a large footer. Maybe it's not a problem currently though. Up for discussion.

**Comment by eyesurewould** [comment]
I personally don't mind a large footer and it's very clear to the user. A menu just hides things and if I've already scrolled that far I probably don't mind scrolling 200px more.

**Comment by buildabeer** [comment]
That's fair, this can be closed then.

**Comment by eyesurewould** [comment]
Sounds good. Unfortunately, I'm not able to close this since it's not assigned to me. Please close or assign.

**Comment by buildabeer-admin** [comment]
Huh, didn't know that. Wonder if I can change it.
