### ISSUE TITLE
Authentication with Heroku dev server

### ISSUE THREAD

**Issue by eyesurewould** [buildabeer/buildabeer#56]
I'm using the Heroku-hosted dev instance (located here: https://buildabeer-dev.herokuapp.com/)  and I'm unable to login, register or use forgot password.

**Comment by buildabeer-admin** [comment]
Do either of these work?

  { email: 'admin@example.com', nickname: 'UOne', name: 'User One', password: "superp4ss", admin: true, confirmed_at: DateTime.now },
  { email: 'user@example.com', nickname: 'UTwo', name: 'User One', password: "superp4ss", admin: false, confirmed_at: DateTime.now }

The heroku dyno was missing SendGrid to send out the verification email. It is on now and should work. I'll verify tonight if it did so.

**Comment by buildabeer-admin** [comment]
Those samples do work on the dev dyno. In theory the registration is fixed... It claims to be sending the confirmation email but I haven't seen anything actually come through yet. I have confirmed the production registration email goes through...

**Comment by eyesurewould** [comment]
It's working now, thanks!
