### ISSUE TITLE
Set Up Code of Conduct

### ISSUE THREAD

**Issue by buildabeer** [buildabeer/buildabeer#9]
https://opensource.guide/code-of-conduct/

**Comment by buildabeer** [comment]
https://www.contributor-covenant.org/

**Comment by eyesurewould** [comment]
I think this is resolved. Can it be closed?

**Comment by buildabeer** [comment]
This is referencing something alone the lines of what you see at
contributor-covenant.Org

**Comment by eyesurewould** [comment]
Right. I see a [CODE_OF_CONDUCT.md](https://github.com/eyesurewould/buildabeer/blob/master/CODE_OF_CONDUCT.md) in the project and it references this project. 

Was there something specifically missing? Or am I misunderstanding the issue?

**Comment by buildabeer** [comment]
For some reason I thought there was a way to have people virtually sign it
or something. After reading again this does look sufficient. Closing.
